version: 2.1
executors:
  app-executor:
    docker:
      - image: circleci/node:14.17.0-buster
    working_directory: ~/repo

aliases:
  - &show-current-branch-name
    run:
      name: Show current branch
      command: echo ${CIRCLE_BRANCH}
  - &restore_cache
    restore_cache:
      keys:
        - app-{{ checksum "package.json" }}
        - app-
  - &install-dependencies
    run:
      name: Install dependencies
      command: yarn install
  - &save-cache
    save_cache:
      paths:
        - node_modules
      key: app-{{ checksum "package.json" }}

jobs:
  build:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *restore_cache
      - *install-dependencies
      - *save-cache

  deploy-to-heroku:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - run:
          name: Deploy to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]
            then
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/{HEROKU_APP_PRODUCTION}.git ${CIRCLE_BRANCH}:master -f
            elif [ "${CIRCLE_BRANCH}" == "staging" ]
            then
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/{HEROKU_APP_STAGING}.git ${CIRCLE_BRANCH}:master -f
            else
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/{HEROKU_APP_DEVEROPMENT}.git ${CIRCLE_BRANCH}:master -f
            fi

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy-to-heroku:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - staging
                - main